### PR TITLE
Fixes layout for GitLab Merge Request Links plugin

### LINKED ISSUE #206: GitLab Merge Request Links plugin layout issues
I noticed when using the GitLab Merge Request Links plugin (https://github.com/tf/redmine_merge_request_links) that the element is actually sitting underneath the issue history at larger breakpoints due to it being too wide. Similarly, between 900 & 991 pixels, it isn't filling the available width.

Screenshot examples:

I'd be happy to make a merge request & fix, but should I just make the fix in `src/sass/components/_issue.scss`, or in the minified `stylesheets/application.css` also?

### PR DESCRIPTION
**Pull request by zendamacf**
The width of the GitLab merge request element wasn't matching the width
of the changesets, which it sits above.

This updates the width of the element depending on the breakpoint.
!important is being used because it needs to override the styling of the
plugin.

fixes #206

### CODE REVIEW

**Comment by zendamacf** [comment]
Ready to go!

**Comment by mrliptontea** [comment]
There are a couple of issues still. They may not be that easy to fix.

1. In Redmine 4.1, between `$redmine-responsive-min` and `$screen-md-min` i.e. when window width is 900-991px - it's overlapping the notes
    
2. In Redmine 3.x-4.0, where associated revisions are not in the tab when both are shown, it breaks the layout of the first note - the avatar and icons drop to where offset where revisions start.
    40-revisions

**Comment by zendamacf** [comment]
Yeah, I'm a bit lost on how to fix these ones. I don't have access to a 4.1 instance to test 1.

As for 2, I've tried tinkering around with the `.journal>div>.contextual` positioning to `position: absolute; right: 0`, but that leaves the text overlapping when the sidebar is expanded:


I pushed a change removing the extra padding & margin on `#issue-merge-requests` to match up with `#issue-changesets`, although that doesn't seem to really do anything with the `.contextual` element.

Any ideas?

**Comment by mrliptontea** [comment]
I use docker-compose to test different versions, there are official Redmine images on Docker Hub.

I think you may need to tinker with the styles of `#history`.

FYI I'm currently away and won't be able to review this for until mid September.

**Comment by zendamacf** [comment]
Realistically I'm not getting back to this, and its pretty old, so I'm closing it.

**Pull request closed without merging**
